### ISSUE TITLE
Compliance Tests Failing 

### ISSUE THREAD

**Issue by cwatsonc** [jelhub/scimgateway#1]
The server is failing the simplecloud.info compliance SCIM 1.1 tests relating to PATCH tests 7-16 when configured for plugin-test.

**Comment by jelhub** [comment]
#7  - Create/delete groups not supported
#8  - Will be fixed in next update (return code 200 with patch content instead of 204 no content)
#9  - XML not supported (Test case says JSON but should be XML)
#10 - Will be fixed in next update (return code 200 with patch content instead of 204 no content)
#11 - XML not supported
#12 - Add member to group is supported, failed because of #7
#13 - Remove member from group is supported, failed because of #12
#14 - XML not supported
#15 - XML not supported
#16 - Unknown test?

**Comment by jelhub** [comment]
v0.3.6:  #7, #8, 10, #12, #13 now success
