### ISSUE TITLE
Problem with modifyUser when user does not exist

### ISSUE THREAD

**Issue by christinedraper** [jelhub/scimgateway#104]
If I do `PUT {{basePath}}/Users/someid` and the user does not exist, then the `modifyUser` plugin is being called with an object that looks like:
```
{
   Resources: [],
   totalResults: 0,
   userName: "xxxx",
   ... other attributes as expected
}
```

This code in scimgateway looks like the cause - if res.Resources it shouldn't do any of the else ifs.
```
        let currentObj = {}
        if (res && res.Resources && Array.isArray(res.Resources) && res.Resources.length === 1) currentObj = res.Resources[0]
        else if (Array.isArray(res) && res.length === 1) currentObj = res[0]
        else if (res && typeof (res) === 'object' && Object.keys(res).length > 0) currentObj = res
```

Even after working around this problem, if the current user doesn't exist, the PUT call should return a 404. I havent been able to figure out how to make it do this vs a 204, 400 or 500.

**Comment by jelhub** [comment]
Put is modifyUser (replace user)
But before this final modifyUser, Put also do misc things like getUser and some merging of current and actual PUT attributes.

If you test using default plugin-loki you get error code 500

I now see that I could return error code 404 when getUser do not contain any user instead of sending a modifyUser and catch that error.

I will look into this.

**Comment by jelhub** [comment]
### v4.2.14
  
[Fixed] 

- PUT now returning 404 instead of 500 when trying to update a user/group that does not exist

**Comment by christinedraper** [comment]
thanks!
