### ISSUE TITLE
createUser is returning userName instead of id

### ISSUE THREAD

**Issue by christinedraper** [jelhub/scimgateway#105]
In my plugin, we're using an ID other than the userName. But when a createUser request happens, the returning user has an id set to the userName, even though getUsers returns the correct ID. And its not returning other attributes.

I think figured out what's happening.  My plugin createUsers is not currently returning a result (I will change this - didnt realize it could because the loki plugin doesnt), and so the scim gateway calls the getUsers method with a userName filter. But the return from that is in the form:
```
{
    Resources: [{ user... }],
    totalResults: 1
}
```
And so the code here: https://github.com/jelhub/scimgateway/blob/master/lib/scimgateway.js#L1199, which expects just the single user to be returned, is not setting the result based on the get and is instead leaving the id set to the userName.

**Comment by dbollaer** [comment]
@jelhub I am experiencing exactly the same problem.
I think the issue happens after creation when the user is queried again.
This returns a list, because the getUsers function is called to retrieve the new user(s).
But I think the code is expecting a single result.
```javascript
        if (obj && obj.id) jsonBody = obj
```
code        
https://github.com/jelhub/scimgateway/blob/f1d84c75cde11828903dcfd380ce51ab3980bc2c/lib/scimgateway.js#L1178

It always return a list from getUsers, because the result of the getUser is being inserted back into an array.

Please let me know, if I can provide additional information, which can help you trouble shoot.

Disclaimer I am not a javascript developer, so I am possibly missing something.
Thank you for having an other look.

I ll continue looking into this and experiment with the loki plugin next.

**Comment by jelhub** [comment]
@dbollaer,
For plugin-loki, id and userName are the same
Take a look at my previous update.

1) createUser should return the full user object or minimum the id.
e.g.: {"id":"xyz"}

2) If id not returned by createUser, gateway will try to lookup user by userName
So, if your plugin does not support query like: `http://localhost:8880/Users?filter=userName eq "bjensen"`
Lookup will fail

3) If both 1 and 2 fails, then returned id will be set to userName instead of blank because custom built endpoints most likely use id=userName

**Comment by dbollaer** [comment]
@jelhub, thank you for your insight. You were completely right in pointing out that I forgot to return my newly created user object.

Context:
I'm developing a library enabling Azure AD tenants to sync their users (source) as guest accounts to our tenant (target). Source users are stored in our tenant with additional extension attributes for userName, externalId, and source (origin).

While Azure AD supports syncing accounts, there is a lack of group support. Additionally, the provisioned groups will receive a prefix to make it clear in the user interface that these groups are provisioned with SCIM.

Next year, we plan several integrations with third-party vendors like Brightspace and Panopto. I'd love to contribute these libraries back. Can I make a PR for each library, or do you prefer I keep my libraries outside the project?

Thank you again for your help!

**Comment by jelhub** [comment]
@dbollaer, PR is always welcome
In next release v4.3.0 i will probably skip returning id if not found or returned by plugin (not using id=userName)
