### ISSUE TITLE
Operator gte not working on Mongo plugin

### ISSUE THREAD

**Issue by fribeiro-keeps** [jelhub/scimgateway#48]
Hello @jelhub ,

First of all, thank you for including the mongodb plugin!
However, I am testing version 4.0.0 and [this](https://github.com/jelhub/scimgateway/blob/v4.0.0/README.md?plain=1#L140) endpoint doesn't return any results.

After taking a look at [this](https://github.com/jelhub/scimgateway/blob/v4.0.0/lib/plugin-mongodb.js#L164), I've tried with "ge" instead. But again, no results found.

Note: At MongoDB, I have the two test mode users (bjensen and jsmith).
Could you run this scenario, please?

Best Regards,
Filipe Ribeiro

**Comment by jelhub** [comment]
Hi,
Both ge and gte works for me.
There is a typo the in documentation, and the correct SCIM operator should be "ge" instead of "gte"

However, MongoDB use gte so both will work.

I think the problem is that you are using an existing DB having testusers that have been previously created (meta.created) by your own plugin, not by v4.0.0

In your plugin, dates was stored as JavaScript objects. In v4.0.0, dates are stored as unix time stamps, giving more flexibility in terms of other products using the same MongoDB.

Try startup with {"persistence": false} and no NODE_ENV set to production. This should give a fresh database that includes test users created by v4.0.0

Regards,
Jarle
