### ISSUE TITLE
Provision auth0 users/groups to Oracle Cloud Infrastructure

### ISSUE THREAD

**Issue by shahidv3** [jelhub/scimgateway#56]
Hi @jelhub 

Thanks for scimgateway.
One question I have is can we provision auth0 users/groups to Oracle Cloud Infra (OCI) since auth0 doesn't support SCIM 2.0 protocol

Please share your thoughts

thanks, shahid

**Comment by jelhub** [comment]
Hi,

SCIM Gateway inbound must be SCIM. Since auth0 doesn't support SCIM, you can't use the Gateway.

If auth0 have some REST API, you could use the SCIM Gateway /api url for none SCIM. Your plugin api-methods could then start SCIM createUser/modifyUser methods located in the same plugin (or in a separate plugin).

You could also look at auth0 as a "HR-system" and integrate with the SCIM Gateway through your own custom code. You read auth0 users/groups and send as SCIM to the Gateway.

Regards,
Jarle

**Comment by shahidv3** [comment]
Thanks @jelhub for the reply.  Its not clear how the users/groups will be provisioned to auth0 federated Idp on OCI. Captured the components as block in below diagram . Please share your thoughts. many thanks, 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/10008362/159296184-c7db3aad-406c-451b-8673-bf1c03d76d34.png">

**Comment by jelhub** [comment]
Hi,
OCI supports SCIM, you could then use plugin-scim as a template.

From diagram it seems that AD is the IdP for auth0. You might consider reading user/groups from AD instead of auth0 e.g. using plugin-ldap.

You may have several plugins running on same gateway or you could merge/build misc. functionality into one plugin.

Regards,
Jarle

**Comment by shahidv3** [comment]
Thanks @jelhub for your response. Appreciate it.

many thanks ,
shahid
