### ISSUE TITLE
password not synced

### ISSUE THREAD

**Issue by shahidv3** [jelhub/scimgateway#59]
Hi @jelhub 

Now with the plugin - ldap I see the users/groups are synched to Oracle IDCS
however when tried to login to OCI console - it throws "Invalid username / password"

do we need to mapping for password attribute as well from SCIM GW to IDCS. please let us know.

many thanks

**Comment by shahidv3** [comment]
Thanks @jelhub for the quick response.

My understanding was SCIM GW (plugin-ldap) will help me to sync users, groups plus user credentials from on-prem AD
Also our objective is to have SSO to OCI using on prem AD credentials without resetting the password.
But looks like we can't sync the existing passwords from on-prem AD using plugin-ldap.

many thanks,

**Comment by jelhub** [comment]
AD and Azure store passwords as hash-values, both using the **same algorithm**, hence passwords (hash) can be synced between AD and Azure.

This password hash cannot be copied to OCI, because Oracle nor SCIM Gateway have accesses to Microsoft’s password algorithm.

It's not possible to convert from hash to clear text (apply to Microsoft also), that's why storing passwords as hash is the preferred way of handling passwords.

Jarle
